- name: Hello World Sample
  hosts: all
  tasks:
  
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
    - name: list contents of directory
        command: ls mydir
        register: contents


