- name: Hello World Sample
  hosts: all
  tasks:
  
  tasks:
  - name: Print debug message
    debug:
      msg: Hello, world!  
  - name: list contents of directory
  command: ls -l /home
  register: contents


